### ISSUE TITLE
MDI icons from v0.5.0

### ISSUE THREAD

**Issue by nagyrobi** [arovak/haspLVGL_demo#3]
I updated the _Jaffa Sunrise sample for openHAB_ jsonl in the documentation to comply with the new MDI icons set coming with v0.5.0. (FA trashed): https://haswitchplate.github.io/openHASP-docs/#integration_openhab/

But since I don't use openHAB and I can't test, I'm just letting here a note that the openHAB configuration files likely have to be updated too with the new icons from: https://haswitchplate.github.io/openHASP-docs/#fonts/

**Comment by arovak** [comment]
Updated the rules to reflect the new icons and syntax for v0.5.0
